config/routes.rb
Rails.application.routes.draw do
 root "posts#index"

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html\
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  match "*unmatched", to: "errors#not_found", via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord


  #validations
  validates :body, presence:true
  

  #relations
  
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord

#validations

  validates :title, presence:true, length:{ minimum: 3, maximum: 50 }
  validates :body, presence:true, length:{ minimum: 3, maximum: 50 }

#relations

  has_many :comments, dependent: :destroy
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #relationsE
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  def after_sign_out_path_for(resource_or_scope)
    posts_path 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find_by(id: params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post 
    else
      redirect_to @post, alert: "Comment cannot be blank."
    end
  end

  
  def destroy
    @comment = current_user.comments.find_by(id: params[:id])

    unless @comment
      redirect_back fallback_location: root_path, alert: "Comment not found."
      return #required because redirect_back doesnt return 
    end

    unless @comment.user == current_user
      redirect_to @comment.post, alert: "You are not authorized to delete this comment."
      return
    end

    if @comment.destroy
      redirect_to @comment.post, notice: "Comment deleted successfully."
    else
      redirect_to @comment.post, alert: "Something went wrong. Could not delete comment."
    end
  end

  private 

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render file: Rails.root.join("public", "404.html"),
           status: :not_found,
           layout: false
  end

  def internal_error
    render file: Rails.root.join("public", "500.html"),
           status: :internal_server_error,
           layout: false
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# before action
before_action :authenticate_user!, except:[ :index, :show]
before_action :load_post, only: [:show, :edit, :update, :destroy]




# handlers

  def index
    @posts = Post.all
  end

  def show
  end
  
  def new
    @post= Post.new
  end
  
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post Deleted"
  end



  private 

  def load_post
    @post = current.posts.find_by(id: params[:id])

    if @post.nil?
      redirect_to posts_path, alert: "Page not founds"
    end
  end
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Article</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      Logged in as: <%= current_user.email %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    <hr>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <div style="color: red; border: 1px solid red; padding: 10px;">
    <h3><%= pluralize(post.errors.count, "error") %> prevented the post from saving:</h3>

    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to "New Post", new_post_path %>

<ul>
<% @posts.each do |post| %>
	<li>
		<%= link_to post.title, post_path(post) %>
  </li>
<%end%>
</ul>

app/views/posts/new.html.erb
<h1>New Article</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to "Back", posts_path %> |
<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>


<h3>Comments:</h3>

<% @post.comments.each do |comment| %>
  <p>
    <strong><%= comment.user.email %>:</strong>
    <%= comment.body %>

    <% if comment.user == current_user %>
      <%= link_to "Delete", post_comment_path(@post, comment),
          method: :delete,
          data: { confirm: "Delete this comment?" } %>
    <% end %>
  </p>
<% end %>

<% if user_signed_in? %>
  <h4>Add a Comment:</h4>
  <%= form_with(model: [@post, Comment.new]) do |f| %>
    <div>
      <%= f.text_area :body, rows: 3 %>
    </div>
    <%= f.submit "Post Comment" %>
  <% end %>
<% else %>
  <p>You must <%= link_to "login", new_user_session_path %> to comment.</p>
<% end %>